volumes:
  data:

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5423
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  inventory:
    env_file:
      - .env
    build: 
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
networks:
  backend: